name: 'Deploy to Google App Engine'
description: 'This action allows you publish an application to Google App Engine'
inputs:
  service_account:
    description: 'Service account file'
    required: true
  project_id:
    description: 'Project id'
    required: true
  debug:
    description: 'Debug action'
    default: ''
  gae_config_path:
    description: 'Path to the yaml file'
    required: true
    default: './app.yaml'
  no_cache:
    description: 'Disable cache'
    required: false
  dispatch_yaml:
    description: 'dispatch.yaml path (optional)'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'server.js'
branding:
  icon: 'box'
  color: 'blue'