name: kadirtereci/graphql-backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install dependencies and build app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: NPM install
        run: npm install 

      - name: Build App
        run: npm run build 

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GCP

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: NPM install
        run: npm install 

      - name: Build App
        run: npm run build 

      - id: "auth"
        name: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: "deploy"
        name: "deployment"
        uses: "google-github-actions/deploy-appengine@v0"
