  name: Test PR Changes

  on:
    pull_request:
      branches:
        - main
        - dev

  jobs:
    test-api:
      runs-on: ubuntu-latest
      name: Install dependencies and build app

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - id: setup-node
          name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 14

        - name: Install Packages
          run: npm install

        - name: Build
          run: npm run build